@extends('layouts.admin')

@section('header')
<h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
    {{ __('Dashboard') }}
</h2>
@endsection

@section('content')
<div class="mb-4 flex justify-between items-center">
    <!-- Add a call to action or a quick summary of the dashboard -->
    <h1 class="text-4xl pb-1 font-bold transition-all duration-500 ease-in-out transform hover:invert"
        style="background: linear-gradient(120deg, #5900ff, #00eeff);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        background-clip: text;
        text-fill-color: transparent;">
        Overview of your business metrics at a glance!
    </h1>
</div>

<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
    <!-- Total Orders -->
    <div class="bg-gray-800 dark:bg-gray-900 border border-gray-700 overflow-hidden shadow-sm sm:rounded-lg p-6 text-center transition-all duration-500 hover:bg-gray-600 dark:hover:bg-gray-800">
        <i class="fas fa-shopping-cart text-teal-400 text-3xl mb-4"></i>
        <h3 class="text-gray-200 text-lg mb-4">Total Orders</h3>
        <p class="text-3xl text-teal-500">{{ $totalOrders }}</p>
        <p class="text-gray-400">The total number of orders received over all time.</p>
    </div>    

    <!-- Total Products -->
    <div class="bg-gray-800 dark:bg-gray-900 border border-gray-700 overflow-hidden shadow-sm sm:rounded-lg p-6 text-center transition-all duration-500 hover:bg-gray-600 dark:hover:bg-gray-800">
        <i class="fas fa-box text-blue-400 text-3xl mb-4"></i>
        <h3 class="text-gray-200 text-lg mb-4">Total Products</h3>
        <p class="text-3xl text-blue-500">{{ $totalProducts }}</p>
        <p class="text-gray-400">The number of different products available in your inventory.</p>
    </div>

    <!-- Total Users -->
    <div class="bg-gray-800 dark:bg-gray-900 border border-gray-700 overflow-hidden shadow-sm sm:rounded-lg p-6 text-center transition-all duration-500 hover:bg-gray-600 dark:hover:bg-gray-800">
        <i class="fas fa-users text-green-400 text-3xl mb-4"></i>
        <h3 class="text-gray-200 text-lg mb-4">Total Users</h3>
        <p class="text-3xl text-green-500">{{ $totalUsers }}</p>
        <p class="text-gray-400">The total number of registered users on your platform.</p>
    </div>

    <!-- Total Reviews -->
    <div class="bg-gray-800 dark:bg-gray-900 border border-gray-700 overflow-hidden shadow-sm sm:rounded-lg p-6 text-center transition-all duration-500 hover:bg-gray-600 dark:hover:bg-gray-800">
        <i class="fas fa-star text-yellow-400 text-3xl mb-4"></i>
        <h3 class="text-gray-200 text-lg mb-4">Total Reviews</h3>
        <p class="text-3xl text-yellow-500">{{ $totalReviews }}</p>
        <p class="text-gray-400">The total number of product reviews submitted by users.</p>
    </div>

    <!-- Total Revenue -->
    <div class="bg-gray-800 dark:bg-gray-900 border border-gray-700 overflow-hidden shadow-sm sm:rounded-lg p-6 text-center transition-all duration-500 hover:bg-gray-600 dark:hover:bg-gray-800">
        <i class="fas fa-dollar-sign text-purple-400 text-3xl mb-4"></i>
        <h3 class="text-gray-200 text-lg mb-4">Total Revenue</h3>
        <p class="text-3xl text-purple-500">Rp. {{ $totalRevenue }}</p>
        <p class="text-gray-400">The total revenue generated from sales over all time.</p>
    </div>

    <!-- Revenue from Product with Highest Revenue -->
    <div class="bg-gray-800 dark:bg-gray-900 border border-gray-700 overflow-hidden shadow-sm sm:rounded-lg p-6 text-center transition-all duration-500 hover:bg-gray-600 dark:hover:bg-gray-800">
        <i class="fas fa-chart-line text-red-400 text-3xl mb-4"></i>
        <h3 class="text-gray-200 text-lg mb-4">Revenue from Top Product</h3>
        <p class="text-3xl text-red-500">Rp. {{ $topProductRevenue }}</p>
        <p class="text-gray-400">The revenue generated by the product with the highest sales.</p>
    </div>

    <!-- Average Order Value -->
    <div class="bg-gray-800 dark:bg-gray-900 border border-gray-700 overflow-hidden shadow-sm sm:rounded-lg p-6 text-center transition-all duration-500 hover:bg-gray-600 dark:hover:bg-gray-800">
        <i class="fas fa-credit-card text-teal-400 text-3xl mb-4"></i>
        <h3 class="text-gray-200 text-lg mb-4">Average Order Value</h3>
        <p class="text-3xl text-teal-500">{{ $averageOrderValue }}</p>
        <p class="text-gray-400">The average value of all orders placed.</p>
    </div>

    <!-- Average Review Rating -->
    <div class="bg-gray-800 dark:bg-gray-900 border border-gray-700 overflow-hidden shadow-sm sm:rounded-lg p-6 text-center transition-all duration-500 hover:bg-gray-600 dark:hover:bg-gray-800">
        <i class="fas fa-star-half-alt text-yellow-400 text-3xl mb-4"></i>
        <h3 class="text-gray-200 text-lg mb-4">Average Review Rating</h3>
        <p class="text-3xl text-yellow-500">{{ number_format($averageRating, 1) }}</p>
        <p class="text-gray-400">The average rating given by users for all products.</p>
    </div>
</div>

<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
    <!-- Reviews Chart -->
    <div class="bg-gray-800 dark:bg-gray-900 border border-gray-700 overflow-hidden shadow-sm sm:rounded-lg p-6 transition-colors duration-300 hover:bg-gray-600 dark:hover:bg-gray-800">
        <h3 class="text-gray-200 text-lg mb-4">Reviews Rating Distribution</h3>
        <div style="height: 300px; width: 100%; display: flex; justify-content: center; align-items: center;">
            <canvas id="reviewsChart" style="max-width: 100%; height: auto;"></canvas>
        </div>
        <p class="text-gray-400 text-sm mt-4">Distribution of review ratings from 1 to 5 stars.</p>
    </div>

    <!-- Orders Chart -->
    <div class="bg-gray-800 dark:bg-gray-900 border border-gray-700 overflow-hidden shadow-sm sm:rounded-lg p-6 transition-colors duration-300 hover:bg-gray-600 dark:hover:bg-gray-800">
        <h3 class="text-gray-200 text-lg mb-4">Orders Per Month</h3>
        <canvas id="ordersChart"></canvas>
        <p class="text-gray-400 text-sm mt-4">Monthly distribution of orders throughout the year.</p>
    </div>
</div>

<div class="bg-gray-800 dark:bg-gray-900 border border-gray-700 overflow-hidden shadow-sm sm:rounded-lg p-6 mt-8 transition-colors duration-300 hover:bg-gray-600 dark:hover:bg-gray-800">
    <h3 class="text-gray-200 text-lg mb-4">Top 10 Products by Revenue</h3>
    <canvas id="topProductsChart"></canvas>
    <p class="text-gray-400 text-sm mt-4">Ranking of top products based on revenue generated.</p>
</div>

<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mt-8">
    <!-- Orders by Status -->
    <div class="bg-gray-800 dark:bg-gray-900 border border-gray-700 overflow-hidden shadow-sm sm:rounded-lg p-6 transition-colors duration-300 hover:bg-gray-600 dark:hover:bg-gray-800">
        <h3 class="text-gray-200 text-lg mb-4">Orders by Status</h3>
        <table class="min-w-full divide-y divide-gray-700">
            <thead class="bg-gray-700">
                <tr>
                    <th class="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider">Status</th>
                    <th class="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider">Count</th>
                </tr>
            </thead>
            <tbody class="bg-gray-800 divide-y divide-gray-700">
                @foreach ($ordersByStatus as $status => $count)
                    <tr class="transition-colors duration-300 hover:bg-gray-800 dark:hover:bg-gray-900">
                        <td class="px-6 py-4 whitespace-nowrap text-gray-300">{{ $status }}</td>
                        <td class="px-6 py-4 whitespace-nowrap text-gray-300">{{ $count }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        <p class="text-gray-400 text-sm mt-4">Overview of the number of orders in each status category.</p>
    </div>

    <!-- Most Popular Products -->
    <div class="bg-gray-800 dark:bg-gray-900 border border-gray-700 overflow-hidden shadow-sm sm:rounded-lg p-6 transition-colors duration-300 hover:bg-gray-600 dark:hover:bg-gray-800">
        <h3 class="text-gray-200 text-lg mb-4">Most Popular Products</h3>
        <table class="min-w-full divide-y divide-gray-700">
            <thead class="bg-gray-700">
                <tr>
                    <th class="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider">Product</th>
                    <th class="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider">Quantity Sold</th>
                </tr>
            </thead>
            <tbody class="bg-gray-800 divide-y divide-gray-700">
                @foreach ($mostPopularProducts as $productId => $quantity)
                    <tr class="transition-colors duration-300 hover:bg-gray-800 dark:hover:bg-gray-900">
                        <td class="px-6 py-4 whitespace-nowrap text-gray-300">{{ \Illuminate\Support\Str::limit($mostPopularProductNames[$productId], 15) }}</td>
                        <td class="px-6 py-4 whitespace-nowrap text-gray-300">{{ $quantity }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        <p class="text-gray-400 text-sm mt-4">These products are frequently purchased by users and show high demand.</p>
    </div>

    <!-- Revenue by Category -->
    <div class="bg-gray-800 dark:bg-gray-900 border border-gray-700 overflow-hidden shadow-sm sm:rounded-lg p-6 transition-colors duration-300 hover:bg-gray-600 dark:hover:bg-gray-800">
        <h3 class="text-gray-200 text-lg mb-4">Revenue by Category</h3>
        <table class="min-w-full divide-y divide-gray-700">
            <thead class="bg-gray-700">
                <tr>
                    <th class="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider">Category</th>
                    <th class="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider">Revenue</th>
                </tr>
            </thead>
            <tbody class="bg-gray-800 divide-y divide-gray-700">
                @foreach ($revenueByCategory as $categoryName => $revenue)
                    <tr class="transition-colors duration-300 hover:bg-gray-800 dark:hover:bg-gray-900">
                        <td class="px-6 py-4 whitespace-nowrap text-gray-300">{{ \Illuminate\Support\Str::limit($categoryName, 10) }}</td>
                        <td class="px-6 py-4 whitespace-nowrap text-gray-300">Rp. {{ \App\Helpers\CurrencyHelper::formatCurrency($revenue) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        <p class="text-gray-400 text-sm mt-4">Shows revenue distribution across different product categories, helping to identify profitable areas.</p>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js"></script>
<script>
    // Function to create a pie chart
    function createPieChart(context, data, labels, colors) {
        return new Chart(context, {
            type: 'pie',
            data: {
                labels: labels,
                datasets: [{
                    data: data,
                    backgroundColor: colors.background,
                    borderColor: colors.border,
                    borderWidth: 1
                }]
            },
            options: {
                responsive: true,
                plugins: {
                    legend: { position: 'top' },
                    tooltip: {
                        backgroundColor: 'rgba(0,0,0,0.7)',
                        titleColor: '#fff',
                        bodyColor: '#fff'
                    }
                }
            }
        });
    }

    // Function to create a bar chart
    function createBarChart(context, data, labels, label, colors) {
        return new Chart(context, {
            type: 'bar',
            data: {
                labels: labels,
                datasets: [{
                    label: label,
                    data: data,
                    backgroundColor: colors.background,
                    borderColor: colors.border,
                    borderWidth: 1
                }]
            },
            options: {
                responsive: true,
                scales: {
                    x: { beginAtZero: true },
                    y: { beginAtZero: true }
                },
                plugins: {
                    tooltip: {
                        backgroundColor: 'rgba(0,0,0,0.7)',
                        titleColor: '#fff',
                        bodyColor: '#fff'
                    }
                }
            }
        });
    }

    // Initialize charts on DOM content loaded
    document.addEventListener('DOMContentLoaded', function () {
        // Reviews Rating Distribution Pie Chart
        var reviewsCtx = document.getElementById('reviewsChart').getContext('2d');
        createPieChart(reviewsCtx, [
            {{ $reviewStats[1] ?? 0 }},
            {{ $reviewStats[2] ?? 0 }},
            {{ $reviewStats[3] ?? 0 }},
            {{ $reviewStats[4] ?? 0 }},
            {{ $reviewStats[5] ?? 0 }}
        ], ['1 Star', '2 Stars', '3 Stars', '4 Stars', '5 Stars'], {
            background: [
                'rgba(255, 99, 132, 0.7)',  // Red
                'rgba(255, 159, 64, 0.7)',  // Orange
                'rgba(255, 205, 86, 0.7)',  // Yellow
                'rgba(75, 192, 192, 0.7)',  // Teal
                'rgba(54, 162, 235, 0.7)'   // Blue
            ],
            border: [
                'rgba(255, 99, 132, 1)',
                'rgba(255, 159, 64, 1)',
                'rgba(255, 205, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(54, 162, 235, 1)'
            ]
        });

        // Orders Per Month Bar Chart
        var ordersCtx = document.getElementById('ordersChart').getContext('2d');
        createBarChart(ordersCtx, [
            {{ $monthlyOrders[1] }},
            {{ $monthlyOrders[2] }},
            {{ $monthlyOrders[3] }},
            {{ $monthlyOrders[4] }},
            {{ $monthlyOrders[5] }},
            {{ $monthlyOrders[6] }},
            {{ $monthlyOrders[7] }},
            {{ $monthlyOrders[8] }},
            {{ $monthlyOrders[9] }},
            {{ $monthlyOrders[10] }},
            {{ $monthlyOrders[11] }},
            {{ $monthlyOrders[12] }}
        ], ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], '# of Orders', {
            background: 'rgba(54, 162, 235, 0.7)',  // Blue
            border: 'rgba(54, 162, 235, 1)'
        });

        // Top Products by Revenue Bar Chart
        var topProductsCtx = document.getElementById('topProductsChart').getContext('2d');
        createBarChart(topProductsCtx, @json(array_values($topProducts)), @json(array_values($topProductNames)), 'Revenue (Rp)', {
            background: 'rgba(255, 99, 132, 0.7)',  // Red
            border: 'rgba(255, 99, 132, 1)'
        });
    });
</script>

@endsection
